# Site settings
title: StagesTrailMN
email: your-email@domain.com
description: >
  Stages de trail en Montagne Noire.

baseurl: "/stmn" # the subpath of your site, e.g. /blog/
url: https://stagetmn.github.io/stmn # the base hostname & protocol for your site
git_address: https://github.com/aksakalli/jekyll-doc-theme
git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: stages

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: infos
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /stages/:year/:month/:day/:title/
    output: true
